# Name: Jawad Hassan
# Section: Bs Ai
# Roll No: 2230-0035
# Teacher: Ms. Salma
#Lab: 4


In [ ]:
#task1
def count_even_odd(numbers):
  even=0
  odd=0
  for i in numbers:
    if i%2==0:
      even+=1
    else:
      odd+=1
  print('even count:',even)
  print('odd count:',odd)
numb=[1,2,3,4,5,6,7,8,9]
count_even_odd(numb)

even count: 4
odd count: 5


In [ ]:
#task2
def analyze_string(s):
  vowels=0
  consonants=0
  digits=0
  special=0
  for i in s:
    if i.lower()=='a' or i.lower()=='e' or i.lower()=='i' or i.lower()=='o' or i.lower()=='u':
      vowels+=1
    elif i.isalpha():
      consonants+=1
    elif i.isdigit():
      digits+=1
    else:
      special+=1
  print('vowels:',vowels)
  print('consonants:',consonants)
  print('digits:',digits)
  print('special:',special)
alphas='IAmgrea8_boy*'
analyze_string(alphas)

vowels: 5
consonants: 5
digits: 1
special: 2


In [ ]:

#task3
def find_max(t):
  max=t[0]
  for i in t:
    if i>max:
      max=i
  return max
tup=(1,2,3,4,5)
print('max:',find_max(tup))

max: 5


In [ ]:
#task4
def search_student(record,name):
  rec=False
  for sname,marks in record.items():
    if sname==name:
      print('marks:',marks)
      rec=True
  if rec==False:
    print('record not found')
dic={
    'jawad':88,
    'ali':60,
    'irfan':33,
    'ahmed':40
    }
search_student(dic,'jawad')
search_student(dic,'faraz')

marks: 88
record not found


In [ ]:
#task5
def filter_greater_than(lst,threshold):
  thrsh=False
  for i in lst:
    if i>threshold:
      print(i,end=' ')
      thrsh=True
  if thrsh==False:
    print('no numbers greater than threshold')
numbs=[1,2,3,4,5,6,7,8]
filter_greater_than(numbs,4)

5 6 7 8 

In [ ]:
#task6
def is_palindrome(word):
  if word[::-1]==word:
    print('palindrome:',word)
  else:
    print('not palindrome:',word)
is_palindrome('football')
is_palindrome('level')

not palindrome: football
palindrome: level


In [ ]:
#task7
def char_frequency(text):
  freq={}
  for i in text:
    if i not in freq:
      freq[i]=1
    else:
      freq[i]+=1
  print('count of characters:',freq)
char_frequency('hello how are u')

count of characters: {'h': 2, 'e': 2, 'l': 2, 'o': 2, ' ': 3, 'w': 1, 'a': 1, 'r': 1, 'u': 1}


In [ ]:
#task8
import custommath as cm
print(cm.factorial(int(input('enter num for factorial:'))))
print(cm.fibonacci(int(input('enter num for fibonacci:'))))
a,b=map(int,input('enter for gcd a and b:').split())
print(cm.gcd (a,b))



enter num for factorial:5
120
enter num for fibonacci:6
8
enter for gcd a and b:6 4
2


In [ ]:
#activityLab
def uniqueval(a):
  unique=[]
  for i in a:
    if i not in unique:
      unique.append(i)
  return unique

listt=[1,2,2,3,4,4,5,6]
a=uniqueval(listt)
print(a)

[1, 2, 3, 4, 5, 6]


In [ ]:
def createdic(n):
  squaredic={}
  for i in range(1,n+1):
    squaredic[i]=i**2

  for i,val in squaredic.items():
    print(i,':',val)
createdic(10)

1 : 1
2 : 4
3 : 9
4 : 16
5 : 25
6 : 36
7 : 49
8 : 64
9 : 81
10 : 100


In [ ]:
def prodtuple(t):
  prod=1
  for i in t:
    prod*=i
  print(prod)
prodtuple((1,2,3,4))

24


In [ ]:
#labactivity
a=input('enter integers:').split()
print(a)
for i in range(len(a)):
  print(a[i])


enter integers:1 2 3 4 5
['1', '2', '3', '4', '5']
1
2
3
4
5


In [ ]:
def main():
  a=input('integers:')
  a=a.split()
  for i in range (len(a)):
    a[i]=int(a[i])
  print('avg is:',avglist(a))
def avglist(l):
  sum=0
  k=len(l)
  for i in l:
    sum+=i
  return sum/k
main()

integers:1 2 3 4 5
avg is: 3.0


In [ ]:
#pass by ref
def main():
  a=input('integers:')
  a=a.split()
  for i in range (len(a)):
    a[i]=int(a[i])
  seta={1,2,3,4,5,1}
  dicta={'a':1,'b':2}
  changel(a,seta,dicta)
  enumerate(a)
  print('list is:',a)
  print(seta)
  print(dicta)
def changel(l,m,n):
  l[0]=1000
  m.add(500)
  n['a']=40

main()

integers:1 2 3 4 5
list is: [1000, 2, 3, 4, 5]
{1, 2, 3, 4, 5, 500}
{'a': 40, 'b': 2}


In [ ]:
def main():
  print('name is:',tell())
def tell():
  return input('name:')
main()

name:jawad
name is: jawad


In [ ]:
m=1
def main():
  x=10;y=5
  a,b=adddif(x,y)
  print('sum',a)
  print('dif',b)
  print('m',m)
def adddif(x,y):
  sum=x+y
  dif=x-y
  global m
  print(m)
  m=m+10
  return sum,dif
main()

1
sum 15
dif 5
m 11


In [ ]:
mylist=[1,2,3,4,5]
square=list(map(lambda x:x**2,mylist))
f1= lambda x:x**2
def power(x):
  return x**2,x**3,x**4
a,b,c=power(2)
print(a,b,c)
print(f1(2))
print(square)


4 8 16
4
[1, 4, 9, 16, 25]


In [ ]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])
print(a[0:,2])
print(a.sum(axis=0))
print(a.sum(axis=1))
for index, i in enumerate(a):
  print(i)
b=np.array([(7,8,9),(10,11,12)])
np.shape(a)
np.size(a)
np.vstack((a,b))
np.hstack((a,b))

[3 6]
[5 7 9]
[ 6 15]
[1 2 3]
[4 5 6]


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
#built in
print(len('hello world'))
a=[1,2,3,4,5]
print(len(a))
print(sum(a))
print(min(a))
print(max(a))
print(abs(-10))
print(round(120.333,2))

11
5
15
1
5
10
120.33


In [22]:
def printhe():
  print('hello')
printhe()
def hel(name):
  print('helloe',name)
hel('ali')

def summ(a,b):
  return a+b
print(summ(2,3))


def summ(a,b):
  c=a+b
  return c
print(summ(2,3))

def ucase(a):
  return a.upper()
print(ucase('i am small'))

def listsum(b):
  return sum(b)
print(listsum([1,2,3,4]))

def printtuple(c):
  print (c)
printtuple(('apple','cherry','fruits'))

def printtuple(c):
  for i in c:
    print(i)
printtuple(('apple','cherry','fruits'))

def printtuple(c):
  for i in c:
    print(i,end=" ")
  print()
printtuple(('apple','cherry','fruits'))

std={'name':'jawad','id':5,'grade':'A'}
def info(s):
  for i,value in s.items():
    print(i,":",value)
info(std)

hello
helloe ali
5
5
I AM SMALL
10
('apple', 'cherry', 'fruits')
apple
cherry
fruits
apple cherry fruits 
name : jawad
id : 5
grade : A


In [32]:
seti={1,2,1,3,4,3,5}
def printset(k):
  for i in k:
    print(i)
printset(seti)

def fact(n):
  i=1
  f=1
  for i in range(1,n+1):
    f=f*i
  return f
print(fact(5))

def fact(n):
  i=2
  f=1
  while i<=n:
    f=f*i
    i+=1
  return f
print(fact(5))

def deuser(name='jay'):
  print('hi ',name)
deuser('ali')
deuser()

def summdef(a=10,b=2):
  return a+b
print(summdef(2,3))
print(summdef())

1
2
3
4
5
120
120
hi  ali
hi  jay
5
12


In [37]:
def powerfunc(i,j=2):
  return i**j

print(powerfunc(4,2))
print(powerfunc(2))

def area(l,w=3):
  return l*w
print(area(2))
print(area(2,4))


16
4
6
8


In [41]:
def student(n,g='C',a=33):
  print('name',n)
  print('grade',g)
  print('age',a)
  print()
student('ali',g='a')
student('ali')
student('ali',g='B',a=30)
student('jawad',40)

name ali
grade a
age 33

name ali
grade C
age 33

name ali
grade B
age 30

name jawad
grade 40
age 33



In [45]:
def cart(i,q=1,p=100):
  t=q*p
  print(i,'q:',q," p:",t)

cart('apple')
cart('banana',4)
cart('banana',10,20)

apple q: 1  p: 100
banana q: 4  p: 400
banana q: 10  p: 200


In [50]:
def calsal(s,t=0.1,b=1000):
  f=s+(b)-(s*t)
  print(f)
calsal(5000)
calsal(5000,b=2000)
calsal(5000,0.2,2000)

5500.0
6500.0
6000.0


In [49]:
def calprice(p,t=0.05,d=0.1):
  f=p+p*t-(p*d)
  print(f)
calprice(100)
calprice(100,t=0.08,d=0.2)

95.0
88.0


In [52]:
def api(url,meth='get',time=30):
  print(url,"meth",meth," t ",time)

api("http://example.com")
api("http://example.com",meth='post',time=10)

http://example.com meth get  t  30
http://example.com meth post  t  10


In [53]:
import math
r=math.sqrt(16)
print(r)


4.0


In [54]:
from math import pi
print(pi)

3.141592653589793


In [55]:
import math as m
print(m.sqrt(81))
print(m.pi)
print(m.factorial(6))


9.0
3.141592653589793
720


In [63]:
import random
print(random.randint(1,10))
print(random.choice(['apple','banana',21]))

9
21


In [73]:
d={
    'ali':20,
    'bilal':50,
    'hasan':90
}
def grade(a):
  for i,j in a.items():
    if j >= 85:
      print('A',i)
    elif j >= 70 and j<= 84:
      print('B',i)
    elif j >= 50 and j<= 69:
      print('C',i)
    else:
      print('f',i)
grade(d)

f ali
C bilal
A hasan


In [75]:
def remdup(l):
 unique=[]
 for i in l:
  if i not in unique:
    unique.append(i)
 return unique

print(remdup([1,2,1,3,4,4,5,3,6,6,1]))

[1, 2, 3, 4, 5, 6]


In [77]:
def dup(n):
 dic={}
 for i in range(1,n+1):
  dic[i]=i**2
 return dic

print(dup(10))

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [81]:
def long(n):
 longest=n[0]
 for i in n:
   if len(i)>len(longest):
     longest=i
 return longest

print(long(['min','max','long','longerrrrr']))

longerrrrr


In [82]:
tup=(2,3,3)
def mul(t):
  p=1
  for i in t:
    p=p*i
  print(p)

mul(tup)

18


In [83]:
def rev(t):
  r=""
  for i in t:
    r=i+r
  print(r)

rev("hello world")

dlrow olleh


In [84]:
def sum_even_odd(a):
  even=0
  odd=0
  for i in a:
    if i%2==0:
      even=even+i
    else:
      odd=odd+i
  print('even:',even)
  print('odd:',odd)
sum_even_odd([1, 2, 3, 4, 5, 6, 7,8,9,10])

even: 30
odd: 25


In [89]:
def check_prime(n):
  if n<=1:
    print('not')
    return
  else:
    div=0
    for i in range(2,n+1):
      if n%i==0:
        div+=1
    if div==1:
      print('prime',n)
    else:
      print('not prime',n)




check_prime(5)

prime 5


In [91]:
def check_prime(n):
  if n<=1:
    print('not')
    return
  else:
    for i in range(2,n):
      if n%i==0:
         print('not prime',n)
         return
    print('prime',n)


check_prime(10)

not prime 10


In [98]:
def find_max_min(n):

  if not n:
    print('empty')
    return
  min=n[0]
  max=n[0]
  for i in n:
    if i>max:
      max=i
    if i<min:
      min=i
  print('max',max)
  print('min',min)


find_max_min([1, 2, 3, 4, 5, 6])
find_max_min([])

max 6
min 1
empty
