# Name: Jawad Hassan
# Section: Bs Ai
# Roll No: 2230-0035
# Teacher: Ms Salma Asif

In [3]:
#task1
import numpy as np
arr=np.random.randint(1,100,20)
print(arr)

[34 32 49 66 28 62 39 92 74 30 27 43 65 57 19 17 75 67 17 59]


In [4]:
#task2
arr=arr.reshape(4,5)
print(arr)

[[34 32 49 66 28]
 [62 39 92 74 30]
 [27 43 65 57 19]
 [17 75 67 17 59]]


In [7]:
#task3
arr2=np.eye(4,4,dtype=int)
print(arr2)
val=np.diag(arr2)
print(val)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[1 1 1 1]


In [15]:
#task4
arr=np.random.randint(0,10,(5,5))
print(arr)
arr[arr%2==0]=-1
print(arr)

[[3 3 2 4 8]
 [9 8 9 0 6]
 [6 6 0 1 0]
 [4 6 2 6 6]
 [6 1 7 9 2]]
[[ 3  3 -1 -1 -1]
 [ 9 -1  9 -1 -1]
 [-1 -1 -1  1 -1]
 [-1 -1 -1 -1 -1]
 [-1  1  7  9 -1]]


In [20]:
#task5
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([2,3,8,9,6,1])
print(arr1)
print(arr2)
common = np.intersect1d(arr1,arr2)
print("Common values:", common)

[1 2 3 4 5 6]
[2 3 8 9 6 1]
Common values: [1 2 3 6]


In [22]:
#task6
arr1=np.random.randint(1,9,(3,4))
arr2=np.random.randint(1,9,(4,2))
print(arr1)
print(arr2)
result=np.dot(arr1,arr2)
print(result)

[[1 3 2 7]
 [1 3 1 7]
 [8 4 8 8]]
[[3 8]
 [1 6]
 [2 5]
 [1 3]]
[[ 17  57]
 [ 15  52]
 [ 52 152]]


In [28]:
#task7
arr1=np.random.random(500)
print(arr1)

[0.25969079 0.79650935 0.12793355 0.66462699 0.62239405 0.39573335
 0.03261542 0.63006534 0.63330392 0.47023688 0.1121022  0.75425053
 0.69491807 0.01440524 0.44149155 0.14250498 0.59778549 0.83104744
 0.7494712  0.46101582 0.59898139 0.53039246 0.18746235 0.20659905
 0.50465107 0.37184164 0.58324227 0.8094676  0.75088671 0.62138813
 0.61473575 0.9463487  0.05921625 0.93132993 0.29492976 0.34810766
 0.1638876  0.25209569 0.98213076 0.10209357 0.58644033 0.32934675
 0.95349257 0.24018465 0.22069968 0.57062377 0.24255429 0.19924301
 0.09196542 0.13319006 0.43410001 0.37066447 0.56045373 0.37354928
 0.18333403 0.68406965 0.24048722 0.70659775 0.19381131 0.40839683
 0.12936564 0.49873288 0.18725215 0.12370288 0.62011311 0.67428669
 0.45753956 0.54322596 0.38584486 0.19717826 0.15556523 0.16582601
 0.47228025 0.99636005 0.11406801 0.55937626 0.77265527 0.81268712
 0.39422679 0.72460944 0.26623442 0.73724025 0.23456481 0.04743107
 0.18251086 0.39716509 0.81242741 0.41331744 0.70493097 0.3263

In [29]:
#task8
arr=np.eye(10,10,dtype=int)
print(arr)


[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [31]:
#task9
np.random.shuffle(arr)
print(arr)

[[0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]]


In [35]:
#task10
arr=np.random.randint(50,150,10)
print(arr)
min=np.min(arr)
max=np.max(arr)
sum=np.sum(arr)
print(min,max,sum)

[141 129 149  64 146 115  57 128 121 147]
57 149 1197
