# CONTENTS
1. NumPy Intro
   * 1.1. Installation
   * 1.2. Importing
2. Creating Arrays
   * 2.1. Creating Arrays from Lists
   * 2.2. Creating Arrays with Functions
3. Array Attributes
   * 3.1. Basic Attributes
   * 3.2. Reshaping Arrays
   * 3.3. Flattening Arrays
4. Grid/Diagonal Matrix
5. Indexing and Slicing
   * 5.1. Indexing
   * 5.2. Slicing
   * 5.3. Indexing in 2D Arrays
6. Random Data
   * 6.1. Generating Random Numbers
7. Basic Functions

## 1. Intro
NumPy stands for Numerical Python and is a Python library used for working with arrays.
In Python, we already have lists that serve the purpose of arrays, but they are slow to process. Hence, 
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists

### 1.1 Installation

In [ ]:
# !pip install numpy

### 1.2. Importing

In [2]:
import numpy as np

## 2. Creating Arrays

### 2.1. Creating Arrays from Lists
Python lists can be converted to NumPy arrays

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array: \n", arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: \n", arr2)


1D array: 
 [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


### 2.2. Creating Arrays with Functions
Different functions can be used to create arrays populated with specific values instead of manually creating them.

In [4]:
arr_zeros = np.zeros((2, 3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
arr_ones = np.ones((3, 2))
print(arr_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
arr_full = np.full((2, 2), 7)
print(arr_full)

[[7 7]
 [7 7]]


In [7]:
arr_range = np.arange(0, 10, 2)
print(arr_range)

[0 2 4 6 8]


In [12]:
arr_linspace = np.linspace(0, 1, 11, endpoint=False)
print(arr_linspace)


[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3. Array Attributes
NumPy supports extracting array attributes from these arrays as well

### 3.1. Basic Attributes

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape = arr.shape
print("The shape of the given array is: ", shape)

The shape of the given array is:  (2, 3)


In [15]:
dimensions = arr.ndim
print("The dimensions of the given array are: ", dimensions)

The dimensions of the given array are:  2


In [16]:
size = arr.size
print("The size of the given array is: ", size)

The size of the given array is:  6


In [17]:
data_type = arr.dtype
print("The datatype of the given array is: ", data_type)

The datatype of the given array is:  int64


### 3.2. Reshaping Arrays

In [18]:
arr_reshaped = arr.reshape(3, 2)
print(arr_reshaped)

[[1 2]
 [3 4]
 [5 6]]


### 3.3. Flattening Arrays

In [19]:
arr_flattened = arr.flatten()
print(arr_flattened)

[1 2 3 4 5 6]


## 4. Grid/Diagonal Matrix

In [20]:
diagonal_matrix = np.diag([1, 2, 3, 4])
print (diagonal_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## 5. Indexing and Slicing

### 5.1. Indexing

In [21]:
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print(arr[0])
print(arr[-1])

10
50


### 5.2. Slicing

In [22]:
arr = np.array([10, 20, 30, 40, 50])

# Slicing
print(arr[1:4])

[20 30 40]


### 5.3. Indexing in 2D Arrays

In [23]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[0, 1])


2


In [24]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[1])


[4 5 6]


### 5.4 Slicing in 2D Arrays

In [25]:
print(arr2)
print("Printing second column")
print(arr2[:, 1])

[[1 2 3]
 [4 5 6]]
Printing second column
[2 5]


### 5.5 Fancy Indexing

In [26]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])  # Access elements at index 0, 2, and 4

[10 30 50]


In [27]:
arr = np.array([[1, 2, 3, 3], [4, 5, 6, 7], [5, 8, 5, 9]])
# array of indices
indices = [0, 2]
fancy = arr[[0, 2], [1, 3]] # row=0,column=1 & row = 2, column = 3
print (fancy)

[2 9]


### 5.6 Boolean Indexing

In [29]:
arr = np.array([[1, 2, 3, 3], [4, 5, 6, 7], [5, 8, 5, 9]])
boolean_condition = arr > 5
print(boolean_condition)
filtered_array = arr[boolean_condition] 
filtered_array

[[False False False False]
 [False False  True  True]
 [False  True False  True]]


array([6, 7, 8, 9])

## 6. Random

### 6.1. Generating Random Numbers

In [30]:
# Random numbers between 0 and 1
random_numbers = np.random.rand(5)
print(random_numbers)

# Random integers
random_integers = np.random.randint(1, 10, size=5)
print(random_integers)

[0.52575818 0.25477817 0.9271191  0.63557553 0.93450502]
[8 8 3 5 6]


## 7. Basic Functions
Some basic NumPy functions are as follows:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Sum
print(np.sum(arr))

# Mean
print(np.mean(arr))

# Standard deviation
print(np.std(arr))

# Minimum value
print(np.min(arr))

# Maximum value
print(np.max(arr))

# Median
print(np.median(arr))

# Variance
print(np.var(arr))
