In [13]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([[1,2,3],[4,5,6]])
print(a1)
print(a2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [21]:
z=np.zeros((2,3))
print(z)
o=np.ones((2,3))
print(o)
o=np.full((3,4),8)
print(o)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [25]:
r=np.arange(2,10,2)
print(r)

[2 4 6 8]


In [27]:
o=np.linspace(0,1,11,endpoint=False)
print(o)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


In [29]:
i=np.eye(10)
print(i)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [33]:
a=np.array([[1,2,3],[4,5,6]])
a.shape
a.ndim
a.size
a.dtype

dtype('int64')

In [37]:
a.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [43]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [46]:
a=np.array([1,2,3,4,7,5,6])
print(a[-1])
print(a[1:4])


6
[2 3 4]


In [51]:
a=np.array([[1,2,3],[4,7,5],[6,10,11]])
print(a[0,1])
print(a[1])
print(a[:,1:])

2
[4 7 5]
[[ 2  3]
 [ 7  5]
 [10 11]]


In [53]:
a=np.array([1,2,3,4,7,5,6])
print(a[[0,3,6]])

[1 4 6]


In [60]:
a=np.array([[1,2,3],[4,7,5],[6,10,11]])
print(a[[0,2],[1,1]])

[ 2 10]


In [62]:
a=np.array([[1,2,3],[4,7,5],[6,10,11]])
print(a>4)
i=a>4
print(a[i])

[[False False False]
 [False  True  True]
 [ True  True  True]]
[ 7  5  6 10 11]


In [75]:
a=np.random.rand(10)
print(a)
a=np.random.randint(1,14,size=10)
print(a)

[0.02765633 0.06646955 0.13447703 0.96882693 0.89675348 0.4133536
 0.25029858 0.83800927 0.79424099 0.17787656]
[ 8 13  3 12  4  4 11  5  9  9]


In [77]:
a=np.array([1,2,3,4,7,5,6])
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.sum(a))
print(np.var(a))
print(np.mean(a))
print(np.median(a))

1
7
2.0
28
4.0
4.0
4.0
